export enum FONT_TYPE {
  Bold = 'Bold',
  Light = 'Light',
  Medium = 'Medium',
  SemiBold = 'SemiBold',
  Regular = 'Regular',
  LatoPrimary = 'LatoPrimary',
  LatoBold = 'LatoBold',
  LatoSemiBold = 'LatoSemiBold',
}

export type FontProps = {
  [type in FONT_TYPE]: string;
};
const Color = {
  burgandyLight: '#EAEAF4',
  burgandyLight80: 'rgba(234, 234, 244, 0.5)',
  purple: '#879CCA',
  purple2: 'rgba(135,156,202,0.18)',
  black: '#333333',
  black2: '#63003D',
  black4: '#1F1F1F',
  black6: '#111111',
  black7: '#161616',
  black8: '#333333',
  grey: '#BFBFBF',
  grey10: '#BEBEBE',
  grey2: '#7C7C7C',
  grey3: '#EEEEEE',
  grey4: '#595959',
  grey5: '#D9D9D9',
  grey7: '#898989',
  grey8: '#F2F2F2',
  grey9: '#FAFAFA',
  grey11: '#D5D5D5', //#D6D6D6
  grey12: '#6F6F6F',
  grey13: '#7D7D7D',
  grey14: '#999999',
  red: '#B4272E',
  lightRed: '#D36E67',
  red2: '#FF715E',
  lightGrey: 'rgba(0, 89, 163, 0.12)',
  darkGrey: '#879CCA',
  transparent: 'transparent',
  white: '#fff',
  ffff: '#FF4081',
  grey100: '#F0F0F0',
  orange: '#F69B00',
  orange2: '#F6D784',
  orange3: '#F7B785',
  grey200: '#EAEAEA',
  overlay: '#00000070',
  lightGreen: '#DFF8EA',
  offWhite: '#FFF8EB',
  blue: '#2869CA',
  lightSkyBlue: '#317CB7',
  darkBlue: '#002441',
  surface: '#F5F5F5',
  green: '#008400',
  InfoBlue: '#2869CA',
  lightGreen1: '#EFF9EB',
  lightGreen2: '#EFF9EB',
  black5: '#111111',
  lightGreen3: '#F2FFF0',
  lightGreen4: '#F1FFFE',
  darkGreen: '#0D6F00',
  lightgrey: '#F5F5F5',
  orange1: '#EF6E0B',
  lightBlue: '#F1F8FF',
  blueDark: '#0059A3',
  grey400: '#343330',
  grey500: '#FCFCFC',
  aliceBlue: '#E6F1F8',
  errorBackground: '#FCEAE8',
  greenLabel: '#37A82B',
  orangeHighlight: '#F7931E',
  blueGreen: '#7ED9D1',
  blueGreen2: '#00948A',
  blackOD: '#111111',
  lightBlack: '#2D2828',
  blackBackground: '#161616',
  blackBorder: '#232323',
  blackBorder45: '#454545',
  whiteD5: '#D5D5D5',
  lighgGreyBackground: '#EBEBEB',
  lightGrey9E: '#9E9E9E',
  errorRed: '#FF9196',
  red3: '#FFF1F3',
  red4: '#E31B54',
  yellow1: '#FFF8EB',
  yellow2: '#AB7F00',
  orange4: '#F49E5C',
  orange5: '#D4620A',
  orange6: '#FFF3E9',
  charcoal: '#333333',
  khakhi: '#A9924B',
  khakhiLight: 'rgba(202,179,109, 0.2)',
};

const lightColors = {
  primaryColor: Color.black2,
  primaryText: Color.black,
  secondaryText: Color.grey2,
  secondaryDarkText: Color.grey4,
  secondaryLightText: Color.grey5,
  secondaryLightText2: Color.grey11,
  secondary3: Color.burgandyLight,
  lightBurgundyBackground: Color.burgandyLight80,
  secondaryDark: Color.purple,
  secondaryShadow: Color.purple2,
  errorText: Color.red,
  errorDarkText: Color.red2,
  defaultText: Color.white,
  linkText: Color.black2,
  successText: Color.green,
  defaultBackground: Color.white,
  darkBackground: Color.black2,
  darkThemeBackground: Color.black6,
  darkThemeLightBackground: Color.black7,
  infoBackground: Color.lightGreen,
  warnBackground: Color.offWhite,
  lightBackground: Color.grey100,
  lightBackground2: Color.grey8,
  lightBackground3: Color.grey11,
  highlightBackground: Color.lightGreen2,
  warnDot: '#F4BE34',
  infoDot: '#4DBB3E',
  border: Color.grey,
  activeBorder: Color.darkGrey,
  errorBorder: Color.lightRed,
  lightBorder: Color.grey3,
  lightBorder2: Color.grey13,
  thinBorder: Color.grey7,
  highlightBorder: Color.lightGrey,
  darkBorder: Color.black2,
  transparent: Color.transparent,
  primaryCTAText: Color.black2,
  buttonPrimary: Color.black2,
  buttonSecondary: Color.white,
  buttonTextPrimary: Color.white,
  buttonTextSecondary: Color.black2,
  buttonPrimaryDisable: Color.grey3,
  buttonDark: Color.grey3,
  buttonDarkDisable: Color.black2,
  buttonSecondaryDisable: Color.white,
  buttonTextPrimaryDisable: Color.grey2,
  buttonTextDark: Color.black2,
  buttonTextDarkDisable: Color.black,
  buttonTextSecondaryDisable: Color.black,
  grey10Text: Color.grey10,
  bgFillBrandSecondaryHover: '#F5F5F555',
  grey100: '#F0F0F0',
  activeIndicator: Color.black2,
  inactiveIndicator: Color.grey200,
  grey300: Color.grey5,
  orange: Color.orange,
  orange50: '#F69B0088',
  warning: Color.orange3,
  highlight: Color.blueGreen,
  modalBackground: '#59595955',
  tabActiveLineColor: Color.black2,
  tabLineInactiveColor: '#EEEEEE',
  tabInactiveTextColor: Color.grey4,
  tabActiveTextColor: Color.black,
  tagColor: Color.green,
  overlay: Color.overlay,
  lightButton: '#EAEAF4',
  secondaryIndicator: Color.lightSkyBlue,
  darkText: Color.black,
  primaryLightBorder: Color.surface,
  secondaryBlack: Color.black4,
  secondaryBlack2: Color.black8,
  primaryDarkText: Color.black2,
  lightBlue: Color.InfoBlue,
  successBackground: Color.lightGreen1,
  errorBackground: Color.errorBackground,
  darkbackground: Color.black5,
  lightGreenBackground: Color.lightGreen3,
  darkGreenText: Color.darkGreen,
  backgroundGrey: Color.lightgrey,
  highLightBorder: Color.orange1,
  secondaryLightBackground: Color.lightBlue,
  primaryDarkBorder: Color.black2,
  successLightBackground: Color.lightGreen1,
  chipsFillUnselect: Color.grey500,
  swipeArrow: '#343330',
  popUpGrey: '#B3B3B3',
  SeparatorColor: '#3C3C435C',
  borderGreen: '#A7E3C2',
  darkBackgroundGrey: '#EAE9E9',
  lightGrey2: '#F9F9F9',
  lightTextGrey: '#696969',
  GreyF2: '#F2F2F2',
  TextInputLabelGreen: Color.greenLabel,
  highlightTextOrange: Color.orangeHighlight,
  highlightTextOrange2: Color.orange4,
  darkBackgroundOD: Color.blackOD,
  thinLabel: Color.lightBlack,
  darkBackground16: Color.blackBackground,
  darkBorderBlack: Color.blackBorder,
  darkBorder1: Color.blackBorder45,
  lightD5: Color.whiteD5,
  GreyEB: Color.lighgGreyBackground,
  Grey9E: Color.lightGrey9E,
  lightError: Color.errorRed,
  Grey99: Color.grey14,
  charcoal: Color.charcoal,
  darkKhakhi: Color.khakhi,
  lightKhakhi: Color.khakhiLight,
};

const darkColors = {
  ...lightColors,
  primaryColor: '#101010',
  primaryText: '#fff',
};

export type ColorType = typeof lightColors | typeof darkColors;

export type ThemeColorProps = {
  light: ColorType;
  dark: ColorType;
};

const ThemeColor: ThemeColorProps = {
  light: lightColors,
  dark: darkColors,
};

const Font: FontProps = {
  Bold: 'Poppins-Bold',
  Light: 'Poppins-Light',
  Medium: 'Poppins-Regular',
  SemiBold: 'Poppins-SemiBold',
  Regular: 'Poppins-Regular',
  LatoPrimary: 'Lato-Regular',
  LatoBold: 'Lato-Black',
  LatoSemiBold: 'Lato-Bold',
};

const Gradient = {
  grey: ['#878787', '#87878700'],
  grey2: ['#ffffff00', '#454545', '#ffffff00'],
  grey3: ['#454545', '#454545'],
  red: ['#FFFFFF', '#E31B54', '#FFFFFF'],
  green: ['#ffffff00', Color.blueGreen2, '#ffffff00'],
  yellow: ['#FFFFFF', '#FDD177', '#FFFFFF'],
  orange: ['#FFFFFF', '#D4620A', '#FFFFFF'],
};

const TYPOGRAPHY = {
  Color,
  Font,
  ThemeColor,
  Gradient,
};

export default TYPOGRAPHY;
